Algoritmo "operadora"

Var

   minutos, multa, valor:real

Inicio

      escreva("Digite a quantidade de minutos:")
      leia(minutos)

      valor <- 50

      se (minutos <= 100) entao
      

      
      escreva("Valor a pagar: R$", valor:3:2)

      senao
      
      multa <- (minutos - 100) * 2
      escreva("Valor a pagar: R$:" , valor + multa:3:2)
      
      fimse
      
      

Fimalgoritmo
